### ISSUE TITLE
App displays directive instead of outputting appropriate html

### ISSUE THREAD

**Issue by lasseborly** [os2display/docs#11]
So I have created an application in my custom bundle and tried to hook it up all the perceived appropriate places.

The actual directory and file structure:
![directory](https://user-images.githubusercontent.com/2671660/43948470-2cfc9c0a-9c8b-11e8-9cb0-03f2af349163.png)

`podcast.json`:

```json
{
  "id": "podcast",
  "type": "slide",
  "name": "DDB CMS Podcast",
  "icon": "podcast.png",
  "paths": {
    "live": "podcast-live.html",
    "edit": "podcast-edit.html",
    "preview": "podcast-preview.html",
    "css": "podcast.css",
    "js": "bundles/kkbding2integration/templates/js/podcastSlide.js"
  },
  "slide_type": "podcast",
  "media_type": "image",
  "script_id": "podcast",
  "orientation": "portrait",
  "ideal_dimensions": {
    "width": "1080",
    "height": "1920"
  },
  "empty_options": {
    "fontsize": 60,
    "responsive_fontsize": 4,
    "bgcolor": "#fff",
    "textcolor": "#4e4a47",
    "headertext": "",
    "infoheadertext": "Månedens udsendelse:",
    "infotext": "",
    "footertext": "Få mere information på ",
    "footerimage": "https://bibliotek.kk.dk/sites/koebenhavn.ddbcms.dk/files/logo1.png"
  },
  "tools": [
    {
      "name": "Overskriftsfarve",
      "id": "header-static-colors"
    },
    {
      "name": "Billede",
      "id": "background-editor-static-colors"
    },
    {
      "name": "Logo",
      "id": "logo-editor"
    }
  ]
}

```

`config/angular.yml`:

```yml
assets:
  js_prod:
    - bundles/kkbding2integration/assets/build/kkbding2integration.min.js

modules:
  dingTools:
    files:
      - bundles/kkbding2integration/apps/dingEditors/background-editor-static-colors.js
      - bundles/kkbding2integration/apps/dingEditors/ding-events-editor.js
      - bundles/kkbding2integration/apps/dingEditors/opening-hours-editor.js
      - bundles/kkbding2integration/apps/dingEditors/text-color-editor.js
      - bundles/kkbding2integration/apps/dingEditors/header-static-colors.js

apps:


```

`header-static-colors.js`:

```javascript
angular.module('toolsModule').directive('headerStaticColors', function(){
  return {
    restrict: 'E',
    replace: true,
    scope: {
      slide:'=',
      close: '&',
      template: '@'
    },
    templateUrl: '/bundles/kkbding2integration/apps/dingEditors/header-static-colors.html'
  };
});
```

`header-static-colors.html`:

```html
<div class="edit-menu" role="banner">
  <a class="edit-menu--overlay is-visible" data-ng-click="close()"></a>
  <div class="edit-menu--inner is-visible">
    <div class="edit-menu--toggle-icon" data-ng-click="close()">X</div>
    <h2 class="edit-menu--header">Redigér tekst</h2>
    <form class="edit-menu--form">
      <label class="edit-menu--label">Overskriftsfarve</label>
      <input colorpicker="rgba" class="edit-menu--form-element" type="text" placeholder="e.g. #fff" data-ng-model="slide.options.textcolor" data-ng-style="{'background-color': slide.options.textcolor}">
    </form>
  </div>
</div>
```

---

That's all well and good and I can get the `Overskriftsfarve` button to appear at the top of my custom slide. Whenever I click it though all I get is the actual directive name instead of the mark-up it's supposed to output.

![static](https://user-images.githubusercontent.com/2671660/43948087-1e018f86-9c8a-11e8-9663-d5b17e49b894.png)

What we really want is something like this:

![static_working](https://user-images.githubusercontent.com/2671660/43948098-295d93de-9c8a-11e8-8179-d58f6f8e9864.png)

It might just be a typo somewhere that I have overlooked but I just can't seem to figure out what I'm missing here. We do have multiple other custom apps out but I can't replicate any of them without getting blocked here.

**Comment by tuj** [comment]
This is because the directive has not been included in the app. 

In
> config/angular.yml:
> 
> assets:
>   js_prod:
>     - bundles/kkbding2integration/assets/build/kkbding2integration.min.js
> 
> modules:
>   dingTools:
>     files:
>       - bundles/kkbding2integration/apps/dingEditors/background-editor-static-colors.js
>       - bundles/kkbding2integration/apps/dingEditors/ding-events-editor.js
>       - bundles/kkbding2integration/apps/dingEditors/opening-hours-editor.js
>       - bundles/kkbding2integration/apps/dingEditors/text-color-editor.js
>       - bundles/kkbding2integration/apps/dingEditors/header-static-colors.js
> 
> apps:
> 

you define dingTools. Is this module injected in ikApp anywhere?

As an example of how to do it, maybe look at https://github.com/itk-os2display/aarhus-data-bundle .
In this bundle I create a new module 'itkDataModule':

https://github.com/itk-os2display/aarhus-data-bundle/blob/develop/Resources/config/angular.yml#L6

and add my directive to it:

https://github.com/itk-os2display/aarhus-data-bundle/blob/develop/Resources/public/apps/itkDataModule/itkDataSourcePicker.js#L1

and inject it in ikApp in:

https://github.com/itk-os2display/aarhus-data-bundle/blob/develop/Resources/config/angular.yml#L11

This in effect injects my module in ikApp. This makes my directive available in the administration.

Hope this helps you solve your issue.

**Comment by lasseborly** [comment]
Thanks for the quick response @tuj! 

What's `ikApp`? And to me it's weird that this would solve the problem since my other tools works ex. `background-editor-static-colors`?

Will try and inject it into `ikApp`! Thanks.

**Comment by lasseborly** [comment]
```yml
assets:
  js_prod:
    - bundles/kkbding2integration/assets/build/kkbding2integration.min.js

modules:
  dingTools:
    files:
      - bundles/kkbding2integration/apps/dingEditors/background-editor-static-colors.js
      - bundles/kkbding2integration/apps/dingEditors/ding-events-editor.js
      - bundles/kkbding2integration/apps/dingEditors/opening-hours-editor.js
      - bundles/kkbding2integration/apps/dingEditors/text-color-editor.js
      - bundles/kkbding2integration/apps/dingEditors/header-static-colors.js

apps:
  ikApp:
    dependencies:
      - dingTools
```

This is what you meant right @tuj ?
